url: https://rust.org.il
repo: https://github.com/szabgab/rust.org.il
branch: main
site_name: Rust in Israel
link_to_source: true
footer: "[Join our newsletter](/mailing-list)! "
tags:
  title: Tags
  description: About Rust and Rust programmers in Israel
archive:
  title: Archive
  description: List of all the articles

authors:
  - name: Gabor Szabo
    nickname: szabgab
    picture: szabgab.png

navbar:
  start:
    - path: /
      title: Home
    - path: /meetings
      title: Meetings
    - path: /projects
      title: Projects
    - path: /mailing-list
      title: Newsletter
    - path: /companies
      title: Companies
    - path: /jobs
      title: Jobs
    - path: /learning
      title: Learning
  end:
    - path: /about
      title: About

